add vj
add vj

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,38 @@
 #!/usr/bin/env bash
 
+
+OUT_PREFIX=$1
+
+# fail hard
+set -o pipefail
+# fail harder
+set -eux
+
+DEFAULT_VERSION="0.4.0"
+dep_version=${VERSION:-$DEFAULT_VERSION}
+dep_dirname=v8js-${dep_version}
+dep_archive_name=${dep_dirname}.tgz
+dep_url=https://pecl.php.net/get/${dep_archive_name}
+
+echo "-----> Building ext/v8js ${dep_version}..."
+
+curl -L ${dep_url} | tar xz
+
+pushd ${dep_dirname}
+export PATH=${OUT_PREFIX}/bin:${PATH}
+export LD_LIBRARY_PATH=${OUT_PREFIX}/lib:${LD_LIBRARY_PATH}
+phpize
+./configure \
+    --prefix=${OUT_PREFIX} \
+    --with-v8js=${OUT_PREFIX}
+make -s -j 9
+# php was a build dep, and it's in $OUT_PREFIX. nuke that, then make install so all we're left with is the extension
+rm -rf ${OUT_PREFIX}/*
+make install -s
+popd
+
+echo "-----> Done."
+
 # grab environment args
 BUILD_DIR=$1
 CACHE_DIR=$2
